import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const cars = [
  { make: "Boeing", model: "747", hp: 9000 },
  { make: "Toyota", model: "Auris", hp: 100 },
  { make: "Honda", model: "Civic", hp: 120 },
  { make: "Ford", model: "Fiesta", hp: 80 },
  { make: "Chevrolet", model: "Cruze", hp: 110 },
  { make: "BMW", model: "320i", hp: 170 },
  { make: "Tesla", model: "Model S", hp: 670 },
  { make: "Lamborghini", model: "Aventador", hp: 730 },
  { make: "Ferrari", model: "458 Italia", hp: 570 },
  { make: "McLaren", model: "720S", hp: 710 },
  { make: "Porsche", model: "911 GT3", hp: 502 },
];

const Home: NextPage = () => {
  const createCars = api.car.create.useMutation();

  const handleClick = () => {
    createCars.mutateAsync(cars);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
        <button
          type="button"
          className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
          onClick={handleClick}
        >
          Create
        </button>
      </main>
    </>
  );
};

export default Home;
