import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const cars = [
  { make: "Boeing", model: "747", hp: 9000 },
  { make: "Toyota", model: "Auris", hp: 100 },
  { make: "Honda", model: "Civic", hp: 120 },
  { make: "Ford", model: "Fiesta", hp: 80 },
  { make: "Chevrolet", model: "Cruze", hp: 110 },
  { make: "BMW", model: "320i", hp: 170 },
  { make: "Tesla", model: "Model S", hp: 670 },
  { make: "Lamborghini", model: "Aventador", hp: 730 },
  { make: "Ferrari", model: "458 Italia", hp: 570 },
  { make: "McLaren", model: "720S", hp: 710 },
  { make: "Porsche", model: "911 GT3", hp: 502 },
];

const Home: NextPage = () => {
  const createCars = api.car.create.useMutation();

  const handleClick = () => {
    createCars.mutateAsync(cars);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <button
          type="button"
          className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
          onClick={handleClick}
        >
          Create
        </button>
      </main>
    </>
  );
};

export default Home;
